format = """
[](fg:#268bd2)\
$directory\
[](fg:#268bd2 bg:#bbc4c4)\
$git_branch\
$git_status\
[](fg:#bbc4c4)\
$fill\
[](fg:#268bd2)\
$time\
[](fg:#268bd2)\
$line_break\
$character"""

[fill]
symbol = ' '

[directory]
style = " bg:#268bd2 fg:#073642"
format = "[ $path ]($style)"
truncation_length = 0

[git_branch]
symbol = ""
style = "bg:#bbc4c4 fg:#073642"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#bbc4c4 fg:#073642"
ahead = '[](fg:#bbc4c4 bg:#c792ea)[  \(+$count\) ](bg:#c792ea fg:#073642)[](fg:#c792ea bg:#bbc4c4)'
staged = '[](fg:#bbc4c4 bg:#c5e478)[ 󰻭 \(+$count\) ](bg:#c5e478 fg:#073642)[](fg:#c5e478 bg:#bbc4c4)'
modified = '[](fg:#bbc4c4 bg:#b38600)[ 󰷫 \(+$count\) ](bg:#b38600 fg:#eee8d5)[](fg:#b38600 bg:#bbc4c4)'
format = "[$all_status$ahead_behind]($style)"

[time]
disabled = false
style = " bg:#268bd2 fg:#073642"
format = "[ $time ]($style)"

[character]
format = "$symbol "
success_symbol = "[❯](bold #2aa198)"
error_symbol = "[](bold #dc322f)"
